# site settings
title: Fundación Ciudadano Inteligente
email: info@ciudadanointeligente.org
description: "Usamos tecnología para transparentar y participar en democracia, trabajamos para trasladar poder desde los pocos hacia los muchos."
baseurl: //ciudadanointeligente.org
basedomain: ciudadanointeligente.org
analytics: 'UA-31247996-1'
jquery_version: "2.1.3"

# build settings
markdown: kramdown
permalink: pretty

collections:
  rockstars:
    output: true
  projects:
    output: true
  board_members:
    output: true
